name: build_umi_hyperos_OneDrivePush
on:
  workflow_dispatch:
    inputs:
      STOCK_URL:
        description: "待操作的底包/xiaomi.eu底包下载地址"
        required: true
      PORT_URL:
        description: "待操作的移植包下载地址"
        required: true
      PACK_TYPE:
        description: "打包类型（EXT/EROFS)，默认EXT"
        required: false
      ENCRYPTION:
        description: "是否解密data分区(TRUE/FALSE)，默认加密"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 最大化构建环境
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: 检出仓库文件
        uses: actions/checkout@main
      - name: 1.准备环境
        run: |
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd openjdk-8-jre android-sdk-libsparse-utils
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome
          pip3 install setuptools
          pip3 install docopt
          pip3 install requests
          pip3 install beautifulsoup4
          pip3 install --ignore-installed pyyaml
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          unzip -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone.zip -d ~/.config/rclone/
      - name: 2.克隆仓库
        run: |
          git clone --depth 1 https://github.com/toraidl/hyperos_port.git -b main hyperos_port
      - name: 3. 开始移植
        run: |
          cd hyperos_port
          if [[ ${{ github.event.inputs.PACK_TYPE }} == "EROFS" ]]; then
              sed -i "s/repack_with_ext4=true/repack_with_ext4=false/" bin/port_config
          fi

          if [[ ${{ github.event.inputs.ENCRYPTION }} == "TRUE" ]]; then
              sed -i "s/remove_data_encryption=false/remove_data_encryption=true/" bin/port_config
          fi
          SIMG2IMG=$(which simg2img)
          cp -rf $SIMG2IMG bin/Linux/x86_64/
          sudo bash port.sh ${{ github.event.inputs.STOCK_URL }} ${{ github.event.inputs.PORT_URL }}
      - name: 4.上传到OneDrive
        run: |
            rclone mkdir onedrive:/MI_Packages/UMI_Packages
            rclone sync -P ./hyperos_port/out/*.zip onedrive:/MI_Packages/UMI_Packages
      - name: 5.删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
